title: Cartolina
description: Open-source 3D cartography for the web
url: https://cartolina.dev
baseurl: ""
cartolina_js:
  base: "https://cdn.tspl.re/libs/cartolina/dist/current/"
  style: "https://cdn.tspl.re/libs/cartolina/dist/current/cartolina.min.css"
  esm_library: "https://cdn.tspl.re/libs/cartolina/dist/current/cartolina.min.esm.js" 
masthead_title: ""
livereload: true
force_polling: true
webrick:
  headers:
    Cache-Control: "no-cache, no-store, must-revalidate"

# Minimal Mistakes via remote_theme
remote_theme: "mmistakes/minimal-mistakes"

# Plugins: include_cache is required to avoid 'Unknown tag include_cached'
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme opts
logo: /assets/images/cartolina-logo-bw.png

search: false
minimal_mistakes_skin: "default"
atom_feed:
  hide: true

# social
social:
  name: "Cartolina"
  links:
    - https://github.com/cartolinadev

twitter:
  username: ondrej1974

og_image: /assets/images/social/default.jpg  

# Navigation
# Top tabs use _data/navigation.yml (collection 'main')
# Optional sidebar can mirror the same 'main' nav by setting 'sidebar: nav: main' in page front matter.
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      toc: false            # right sticky ToC by default
      toc_sticky: true
      classes: wide

exclude:
  - ".#*"
  - "#*#"
  - ".DS_Store"
      
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/cartolinadev/cartolina-js"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/@ondrej1974"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/ondrejprochazka/"

copyright: "Ondřej Procházka, Montevallo Consulting, s.r.o"
      
